[workspace]
members = ["egui-directx9", "egui-directx11", "egui-directx12", "egui-win32"]


[workspace.metadata]
license = "MIT"

[workspace.dependencies]
windows = "0.59.0"
egui = "0.31.1"
arboard = "3.5.0"

# My blessed decisions.
thiserror = "1.0.40"
tracing = "0.1.37"
